"""Remove 'manual' from payment status enum

Revision ID: 2d0765fe4722
Revises: bbb50d9bce74
Create Date: 2026-03-12 01:12:26.924130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0765fe4722'
down_revision: Union[str, Sequence[str], None] = 'bbb50d9bce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
