"""Add user model

Revision ID: 59b7f904137e
Revises: d151ac76ed89
Create Date: 2026-03-09 10:42:10.577997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b7f904137e'
down_revision: Union[str, Sequence[str], None] = 'd151ac76ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('transactions', 'auth_user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='auth_user_id::uuid')
    op.alter_column('transactions', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # create enum type explicitly (SQLAlchemy takes care of checking
    # existence so we don't rely on Postgres-specific IF NOT EXISTS syntax)
    from sqlalchemy.dialects import postgresql

    payment_enum = postgresql.ENUM('gpay', 'phonepe', 'paytm', name='paymentmethodenum')
    payment_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('gpay', 'phonepe', 'paytm', name='paymentmethodenum'),
               existing_nullable=True,
               postgresql_using='payment_method::paymentmethodenum')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_auth_user_id'), 'transactions', ['auth_user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['auth_user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_auth_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.Enum('gpay', 'phonepe', 'paytm', name='paymentmethodenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('transactions', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('transactions', 'auth_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('categories')
    # ### end Alembic commands ###
