"""add_cards_reward_rules_and_card_id_on_transactions

Revision ID: 6b70d8b3c47b
Revises: 2d0765fe4722
Create Date: 2026-03-14 21:29:40.595184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b70d8b3c47b'
down_revision: Union[str, Sequence[str], None] = '2d0765fe4722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('network', sa.Enum('visa', 'mastercard', 'rupay', 'amex', 'diners', name='cardnetwork'), nullable=False),
    sa.Column('card_type', sa.Enum('credit', 'debit', name='cardtype'), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('points_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('point_value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('card_reward_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_pattern', sa.String(length=200), nullable=True),
    sa.Column('reward_type', sa.Enum('points', 'cashback', 'miles', name='rewardtype'), nullable=False),
    sa.Column('earn_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('earn_per', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_cap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_reward_rules_card_id'), 'card_reward_rules', ['card_id'], unique=False)
    op.add_column('transactions', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_card_id'), 'transactions', ['card_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'cards', ['card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_card_id'), table_name='transactions')
    op.drop_column('transactions', 'card_id')
    op.drop_index(op.f('ix_card_reward_rules_card_id'), table_name='card_reward_rules')
    op.drop_table('card_reward_rules')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
